version: 1

jobs:
  build:

    docker:
      - image: mrpossoms/ubuntu-bionic:latest
        environment:

    steps:
      - checkout

      - run:
          name: Run tests
          command: make -C tests test

